Simulink.defineIntEnumType( 'BlinkerValues', ...
   {'off','right','left','hazard'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'off', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

