% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Feb-2015 09:55:29
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
                                         

ign_val = AUTOSAR.Signal;
ign_val.CoderInfo.StorageClass = 'Custom';
ign_val.CoderInfo.Alias = '';
ign_val.CoderInfo.Alignment = -1;
ign_val.CoderInfo.CustomStorageClass = 'PerInstanceMemory';
ign_val.CoderInfo.CustomAttributes.ConcurrentAccess = false;
ign_val.CoderInfo.CustomAttributes.needsNVRAMAccess = false;
ign_val.CoderInfo.CustomAttributes.IsArTypedPerInstanceMemory = true;
ign_val.Description = '';
ign_val.DataType = 'uint8';
ign_val.Min = [];
ign_val.Max = [];
ign_val.DocUnits = '';
ign_val.Dimensions = 1;
ign_val.DimensionsMode = 'Fixed';
ign_val.Complexity = 'real';
ign_val.SampleTime = -1;
ign_val.SamplingMode = 'Sample based';
ign_val.InitialValue = '';
ign_val.SwCalibrationAccess = 'ReadOnly';