% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Feb-2015 11:39:32
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
                                                     

UFIX8_EN4 = Simulink.NumericType;
UFIX8_EN4.Description = '';
UFIX8_EN4.DataScope = 'Auto';
UFIX8_EN4.HeaderFile = 'Rte_Type.h';
UFIX8_EN4.DataTypeMode = 'Fixed-point: slope and bias scaling';
UFIX8_EN4.SignednessBool = false;
UFIX8_EN4.WordLength = 8;
UFIX8_EN4.FixedExponent = -4;
UFIX8_EN4.SlopeAdjustmentFactor = 1;
UFIX8_EN4.Bias = 0;
UFIX8_EN4.DataTypeOverride = 'Inherit';
UFIX8_EN4.IsAlias = true;

